<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="9" hostname="LAPTOP-0H2UAF0N" name="com.webtest.demo.Test_Fore" tests="10" failures="0" timestamp="2020-11-16T14:42:07 CST" time="0.009" errors="1">
  <testcase name="testreg1" time="0.000" classname="com.webtest.demo.Test_Fore">
    <skipped/>
  </testcase> <!-- testreg1 -->
  <system-out/>
  <testcase name="testLogin3" time="0.000" classname="com.webtest.demo.Test_Fore">
    <skipped/>
  </testcase> <!-- testLogin3 -->
  <system-out/>
  <testcase name="testFindPwd" time="0.000" classname="com.webtest.demo.Test_Fore">
    <skipped/>
  </testcase> <!-- testFindPwd -->
  <system-out/>
  <testcase name="testLogin" time="0.000" classname="com.webtest.demo.Test_Fore">
    <skipped/>
  </testcase> <!-- testLogin -->
  <system-out/>
  <testcase name="testreg2" time="0.000" classname="com.webtest.demo.Test_Fore">
    <skipped/>
  </testcase> <!-- testreg2 -->
  <system-out/>
  <testcase name="testreg4" time="0.000" classname="com.webtest.demo.Test_Fore">
    <skipped/>
  </testcase> <!-- testreg4 -->
  <system-out/>
  <testcase name="testreg3" time="0.000" classname="com.webtest.demo.Test_Fore">
    <skipped/>
  </testcase> <!-- testreg3 -->
  <system-out/>
  <testcase name="testLogin2" time="0.000" classname="com.webtest.demo.Test_Fore">
    <skipped/>
  </testcase> <!-- testLogin2 -->
  <system-out/>
  <testcase name="loginout" time="0.009" classname="com.webtest.demo.Test_Fore">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.webtest.demo.Test_Fore.loginout(Test_Fore.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- loginout -->
  <system-out/>
  <testcase name="testreg5" time="0.000" classname="com.webtest.demo.Test_Fore">
    <skipped/>
  </testcase> <!-- testreg5 -->
  <system-out/>
</testsuite> <!-- com.webtest.demo.Test_Fore -->
